using System.Collections.Generic;

namespace BotIskra
{
    public static class ModelsPrivate
    {
        public class TrateBalance
        {
            public TradeBalanceObject BTC { get; set; }
            public TradeBalanceObject ETH { get; set; }
            public TradeBalanceObject USD { get; set; }
            public TradeBalanceObject LTC { get; set; }
            public TradeBalanceObject ETC { get; set; }
            public TradeBalanceObject BCH { get; set; }
            public TradeBalanceObject DASH { get; set; }
            public TradeBalanceObject NEO { get; set; }
            public TradeBalanceObject GAS { get; set; }
            public TradeBalanceObject UAH { get; set; }
            public TradeBalanceObject XLM { get; set; }
            public TradeBalanceObject OMG { get; set; }
            public TradeBalanceObject BNB { get; set; }
            public TradeBalanceObject USDT { get; set; }
            public TradeBalanceObject SNT { get; set; }
            public TradeBalanceObject MKR { get; set; }
            public TradeBalanceObject ZRX { get; set; }
            public TradeBalanceObject BAT { get; set; }
            public TradeBalanceObject WTC { get; set; }
            public TradeBalanceObject WAVES { get; set; }
            public TradeBalanceObject EUR { get; set; }
            public TradeBalanceObject RUB { get; set; }
            public TradeBalanceObject ILC { get; set; }
            public TradeBalanceObject CCOH { get; set; }
            public TradeBalanceObject TRX { get; set; }
            public TradeBalanceObject AYA { get; set; }
            public TradeBalanceObject CSC { get; set; }
            public TradeBalanceObject MATIC { get; set; }
            public TradeBalanceObject XRP { get; set; }
            public TradeBalanceObject BTT { get; set; }
            public TradeBalanceObject WIN { get; set; }
            public TradeBalanceObject NRG { get; set; }
            public TradeBalanceObject AGRS { get; set; }
            public TradeBalanceObject USDT_ETH { get; set; }
            public TradeBalanceObject USDT_TRON { get; set; }
            public TradeBalanceObject TUSD { get; set; }
            public TradeBalanceObject USDC { get; set; }
            public TradeBalanceObject XEM { get; set; }
            public TradeBalanceObject LINK { get; set; }
            public TradeBalanceObject SOLO { get; set; }
            public TradeBalanceObject CAP { get; set; }
            public TradeBalanceObject BSV { get; set; }
            public TradeBalanceObject ZEC { get; set; }
            public TradeBalanceObject DBTC { get; set; }
            public TradeBalanceObject DUSDT { get; set; }
            public TradeBalanceObject TLW { get; set; }
            public TradeBalanceObject TNC { get; set; }
            public TradeBalanceObject MARTK { get; set; }
            public TradeBalanceObject MWC { get; set; }
            public TradeBalanceObject USDT_OMNI { get; set; }
            public TradeBalanceObject FNT { get; set; }
            public TradeBalanceObject ADK { get; set; }
            public TradeBalanceObject RPZX { get; set; }
            public TradeBalanceObject BUBO { get; set; }
            public TradeBalanceObject XMR { get; set; }
            public TradeBalanceObject VRSC { get; set; }
            public TradeBalanceObject INTX { get; set; }
            public TradeBalanceObject HTML { get; set; }
            public TradeBalanceObject GMC { get; set; }
            public TradeBalanceObject BLVR { get; set; }
            public TradeBalanceObject ZEN { get; set; }
            public TradeBalanceObject AMB { get; set; }
            public TradeBalanceObject DOGE { get; set; }
            public TradeBalanceObject AXEL { get; set; }
            public TradeBalanceObject QARK { get; set; }
            public TradeBalanceObject MEDI { get; set; }
            public TradeBalanceObject VIDYA { get; set; }
            public TradeBalanceObject KOCJ { get; set; }
            public TradeBalanceObject COMP { get; set; }
            public TradeBalanceObject YFI { get; set; }
            public TradeBalanceObject SNX { get; set; }
            public TradeBalanceObject DAI { get; set; }
            public TradeBalanceObject SXP { get; set; }
            public TradeBalanceObject BAND { get; set; }
            public TradeBalanceObject KNC { get; set; }
            public TradeBalanceObject UNI { get; set; }
            public TradeBalanceObject NCDT { get; set; }
            public TradeBalanceObject PTOY { get; set; }
            public TradeBalanceObject EOS { get; set; }
            public TradeBalanceObject UTED { get; set; }
            public TradeBalanceObject AWX { get; set; }
            public TradeBalanceObject AQN { get; set; }
            public TradeBalanceObject EVX { get; set; }
            public TradeBalanceObject DIGEX { get; set; }
            public TradeBalanceObject MRX { get; set; }
            public TradeBalanceObject NEEO { get; set; }
            public TradeBalanceObject DYN { get; set; }
            public TradeBalanceObject KALA { get; set; }
            public TradeBalanceObject MVEDA { get; set; }
            public TradeBalanceObject OVO { get; set; }
            public TradeBalanceObject VCG { get; set; }
            public TradeBalanceObject SUN { get; set; }
            public TradeBalanceObject VNLA { get; set; }
            public TradeBalanceObject CFXQ { get; set; }
            public TradeBalanceObject BNOX { get; set; }
            public TradeBalanceObject BLCT { get; set; }
            public TradeBalanceObject ICX { get; set; }
            public TradeBalanceObject HMR { get; set; }
            public TradeBalanceObject JNB { get; set; }
            public TradeBalanceObject PIVX { get; set; }
            public TradeBalanceObject NVZN { get; set; }
            public TradeBalanceObject GRT { get; set; }
            public TradeBalanceObject SLT { get; set; }
            public TradeBalanceObject DAA { get; set; }
            public TradeBalanceObject XSN { get; set; }
            public TradeBalanceObject BOLC { get; set; }
            public TradeBalanceObject EDC { get; set; }
            public TradeBalanceObject FIO { get; set; }
            public TradeBalanceObject AGRS_OMNI { get; set; }
            public TradeBalanceObject AGRS_ETH { get; set; }
            public TradeBalanceObject BSBT { get; set; }
            public TradeBalanceObject XFC { get; set; }
            public TradeBalanceObject RXC { get; set; }
            public TradeBalanceObject BSO { get; set; }
            public TradeBalanceObject HOGE { get; set; }
            public TradeBalanceObject SUPERB { get; set; }
            public TradeBalanceObject PWC { get; set; }
            public TradeBalanceObject TWA { get; set; }
            public TradeBalanceObject AMLT { get; set; }
            public TradeBalanceObject AZU { get; set; }
            public TradeBalanceObject STON { get; set; }
            public TradeBalanceObject LOTTO { get; set; }
            public TradeBalanceObject SFM { get; set; }
            public TradeBalanceObject DOGIRA { get; set; }
            public TradeBalanceObject PIT { get; set; }
            public TradeBalanceObject SMARS { get; set; }
            public TradeBalanceObject FROGE { get; set; }
            public TradeBalanceObject NCAT { get; set; }
            public TradeBalanceObject ASH { get; set; }
            public TradeBalanceObject NTK { get; set; }
            public TradeBalanceObject SFC { get; set; }
            public TradeBalanceObject STRI { get; set; }
            public TradeBalanceObject HLO { get; set; }
            public TradeBalanceObject BNB_BEP2 { get; set; }
            public TradeBalanceObject BNB_BSC { get; set; }
            public TradeBalanceObject XTZ { get; set; }
            public TradeBalanceObject SAFU { get; set; }
            public TradeBalanceObject SPE { get; set; }
            public TradeBalanceObject TYC { get; set; }
            public TradeBalanceObject EARNX { get; set; }
            public TradeBalanceObject HAPPY { get; set; }
            public TradeBalanceObject ORFANO { get; set; }
            public TradeBalanceObject WSBT { get; set; }
            public TradeBalanceObject DECL { get; set; }
            public TradeBalanceObject WCOM { get; set; }
            public TradeBalanceObject HOKK { get; set; }
            public TradeBalanceObject DEEZ { get; set; }
            public TradeBalanceObject PSI { get; set; }
            public TradeBalanceObject PYE { get; set; }
            public TradeBalanceObject SANSHU { get; set; }
            public TradeBalanceObject FLIX { get; set; }
            public TradeBalanceObject POODL2 { get; set; }
            public TradeBalanceObject AQGT { get; set; }
            public TradeBalanceObject STORY { get; set; }
            public TradeBalanceObject HNZO { get; set; }
            public TradeBalanceObject KOJI { get; set; }
            public TradeBalanceObject HZM { get; set; }
            public TradeBalanceObject OCTA { get; set; }
            public TradeBalanceObject USDT_BSC { get; set; }
            public TradeBalanceObject ERS { get; set; }
            public TradeBalanceObject WRT { get; set; }
            public TradeBalanceObject C98 { get; set; }
            public TradeBalanceObject TORG { get; set; }
            public TradeBalanceObject DOT { get; set; }
            public TradeBalanceObject TUSD_ETH { get; set; }
            public TradeBalanceObject TUSD_TRON { get; set; }
            public TradeBalanceObject USDC_ETH { get; set; }
            public TradeBalanceObject USDC_TRON { get; set; }
            public TradeBalanceObject KSM { get; set; }
            public TradeBalanceObject LOFI { get; set; }
            public TradeBalanceObject CHZ { get; set; }
            public TradeBalanceObject TABOO { get; set; }
            public TradeBalanceObject MANA { get; set; }
            public TradeBalanceObject SAND { get; set; }
            public TradeBalanceObject DATA { get; set; }
            public TradeBalanceObject MATIC_POLYGON { get; set; }
            public TradeBalanceObject MATIC_ETH { get; set; }
            public TradeBalanceObject CPIE { get; set; }
            public TradeBalanceObject QTECH { get; set; }
            public TradeBalanceObject PKRFI { get; set; }
            public TradeBalanceObject DBX { get; set; }
            public TradeBalanceObject USDP { get; set; }
            public TradeBalanceObject SUSHI { get; set; }
            public TradeBalanceObject SUSHI_ETH { get; set; }
            public TradeBalanceObject SUSHI_BSC { get; set; }
            public TradeBalanceObject BNT { get; set; }
            public TradeBalanceObject CRV { get; set; }
            public TradeBalanceObject ARV { get; set; }
            public TradeBalanceObject LIFE { get; set; }
            public TradeBalanceObject USDT_EOS { get; set; }
            public TradeBalanceObject BERRY { get; set; }
            public TradeBalanceObject DYDX { get; set; }
            public TradeBalanceObject ANKR { get; set; }
            public TradeBalanceObject ANKR_ETH { get; set; }
            public TradeBalanceObject ANKR_BSC { get; set; }
            public TradeBalanceObject SHIB { get; set; }
            public TradeBalanceObject MTO { get; set; }
            public TradeBalanceObject SOL { get; set; }
            public TradeBalanceObject KLEE { get; set; }
            public TradeBalanceObject RARE { get; set; }
            public TradeBalanceObject CYCE { get; set; }
            public TradeBalanceObject LUFFY { get; set; }
            public TradeBalanceObject SWAPP { get; set; }
            public TradeBalanceObject EMPIRE { get; set; }
            public TradeBalanceObject CXRBN { get; set; }
            public TradeBalanceObject ADA { get; set; }
            public TradeBalanceObject ESHK { get; set; }
            public TradeBalanceObject XNR { get; set; }
            public TradeBalanceObject KISHI { get; set; }
            public TradeBalanceObject PRT { get; set; }
            public TradeBalanceObject DTNG { get; set; }
            public TradeBalanceObject ZAMZAM { get; set; }
            public TradeBalanceObject CCAT { get; set; }
            public TradeBalanceObject SMI { get; set; }
            public TradeBalanceObject MLNK { get; set; }
            public TradeBalanceObject STEMX { get; set; }
            public TradeBalanceObject MONEY { get; set; }
            public TradeBalanceObject FJB { get; set; }
            public TradeBalanceObject MIRAI { get; set; }
            public TradeBalanceObject XRDOGE { get; set; }
            public TradeBalanceObject MTP { get; set; }
            public TradeBalanceObject ALPACA { get; set; }
            public TradeBalanceObject MYL { get; set; }
            public TradeBalanceObject IJZ { get; set; }
            public TradeBalanceObject PXP { get; set; }
            public TradeBalanceObject BREW { get; set; }
            public TradeBalanceObject CT { get; set; }
            public TradeBalanceObject XDC { get; set; }
            public TradeBalanceObject HODL { get; set; }
            public TradeBalanceObject VICA { get; set; }
            public TradeBalanceObject TCG2 { get; set; }
            public TradeBalanceObject FUTURE { get; set; }
            public TradeBalanceObject VET { get; set; }
            public TradeBalanceObject VEED { get; set; }
            public TradeBalanceObject HMETA { get; set; }
            public TradeBalanceObject BLXM { get; set; }
            public TradeBalanceObject LRC { get; set; }
            public TradeBalanceObject AXS { get; set; }
            public TradeBalanceObject EQ { get; set; }
            public TradeBalanceObject NEAR { get; set; }
            public TradeBalanceObject BTCZ { get; set; }
            public TradeBalanceObject GALA { get; set; }
            public TradeBalanceObject FTT { get; set; }
            public TradeBalanceObject AAVE { get; set; }
            public TradeBalanceObject ENJ { get; set; }
            public TradeBalanceObject ENS { get; set; }
            public TradeBalanceObject LPT { get; set; }
            public TradeBalanceObject ALN { get; set; }
            public TradeBalanceObject LUNC { get; set; }
            public TradeBalanceObject SRO { get; set; }
            public TradeBalanceObject RNDR { get; set; }
            public TradeBalanceObject REN { get; set; }
            public TradeBalanceObject SKL { get; set; }
            public TradeBalanceObject SRM { get; set; }
            public TradeBalanceObject YGG { get; set; }
            public TradeBalanceObject MEFA { get; set; }
            public TradeBalanceObject MASK { get; set; }
            public TradeBalanceObject SONO { get; set; }
            public TradeBalanceObject COP { get; set; }
            public TradeBalanceObject FROGEX { get; set; }
            public TradeBalanceObject AVAX { get; set; }
            public TradeBalanceObject AVAX_CCHAIN { get; set; }
            public TradeBalanceObject CENT { get; set; }
            public TradeBalanceObject GLM { get; set; }
            public TradeBalanceObject NOOFT { get; set; }
            public TradeBalanceObject APE { get; set; }
            public TradeBalanceObject TOMO { get; set; }
            public TradeBalanceObject TOMO_ETH { get; set; }
            public TradeBalanceObject TOMO_TOMO { get; set; }
            public TradeBalanceObject TYV { get; set; }
            public TradeBalanceObject TRIBE { get; set; }
            public TradeBalanceObject PYR { get; set; }
            public TradeBalanceObject FIL { get; set; }
            public TradeBalanceObject AKITA { get; set; }
            public TradeBalanceObject JST { get; set; }
            public TradeBalanceObject USTC { get; set; }
            public TradeBalanceObject INJ { get; set; }
            public TradeBalanceObject ANT { get; set; }
            public TradeBalanceObject RAD { get; set; }
            public TradeBalanceObject BOBC { get; set; }
            public TradeBalanceObject STRM { get; set; }
            public TradeBalanceObject CHR { get; set; }
            public TradeBalanceObject SUPER { get; set; }
            public TradeBalanceObject CTSI { get; set; }
            public TradeBalanceObject STORJ { get; set; }
            public TradeBalanceObject RSR { get; set; }
            public TradeBalanceObject MDX { get; set; }
            public TradeBalanceObject REQ { get; set; }
            public TradeBalanceObject OGN { get; set; }
            public TradeBalanceObject MIR { get; set; }
            public TradeBalanceObject POLS { get; set; }
            public TradeBalanceObject PUNDIX { get; set; }
            public TradeBalanceObject WLONG { get; set; }
            public TradeBalanceObject HEC { get; set; }
            public TradeBalanceObject RBT { get; set; }
            public TradeBalanceObject CBO { get; set; }
            public TradeBalanceObject CVC { get; set; }
            public TradeBalanceObject WSD { get; set; }
            public TradeBalanceObject OXT { get; set; }
            public TradeBalanceObject BICO { get; set; }
            public TradeBalanceObject NKN { get; set; }
            public TradeBalanceObject POND { get; set; }
            public TradeBalanceObject XDEN { get; set; }
            public TradeBalanceObject EAI { get; set; }
            public TradeBalanceObject MLN { get; set; }
            public TradeBalanceObject BADGER { get; set; }
            public TradeBalanceObject BAL { get; set; }
            public TradeBalanceObject RLC { get; set; }
            public TradeBalanceObject ALICE { get; set; }
            public TradeBalanceObject KLC { get; set; }
            public TradeBalanceObject VOLT { get; set; }
            public TradeBalanceObject POWR { get; set; }
            public TradeBalanceObject BITCCA { get; set; }
            public TradeBalanceObject IHC { get; set; }
            public TradeBalanceObject QUA { get; set; }
            public TradeBalanceObject QUA_BSC { get; set; }
            public TradeBalanceObject QUA_ETH { get; set; }
            public TradeBalanceObject DNT { get; set; }
            public TradeBalanceObject HBAR { get; set; }
            public TradeBalanceObject JAM { get; set; }
            public TradeBalanceObject MTL { get; set; }
            public TradeBalanceObject GAL { get; set; }
            public TradeBalanceObject STPT { get; set; }
            public TradeBalanceObject UTK { get; set; }
            public TradeBalanceObject IDEX { get; set; }
            public TradeBalanceObject SL { get; set; }
            public TradeBalanceObject GMT { get; set; }
            public TradeBalanceObject EZC { get; set; }
            public TradeBalanceObject KZT { get; set; }
            public TradeBalanceObject AGLD { get; set; }
            public TradeBalanceObject CLV { get; set; }
            public TradeBalanceObject ARPA { get; set; }
            public TradeBalanceObject LINA { get; set; }
            public TradeBalanceObject PHA { get; set; }
            public TradeBalanceObject YFII { get; set; }
            public TradeBalanceObject BLZ { get; set; }
            public TradeBalanceObject AKRO { get; set; }
            public TradeBalanceObject TRB { get; set; }
            public TradeBalanceObject FRONT { get; set; }
            public TradeBalanceObject WNXM { get; set; }
            public TradeBalanceObject FIS { get; set; }
            public TradeBalanceObject DF { get; set; }
            public TradeBalanceObject CVP { get; set; }
            public TradeBalanceObject HDX { get; set; }
            public TradeBalanceObject FOR { get; set; }
            public TradeBalanceObject USDC_XLM { get; set; }
            public TradeBalanceObject UMA { get; set; }
            public TradeBalanceObject KLAY { get; set; }
            public TradeBalanceObject TT { get; set; }
            public TradeBalanceObject LUNA { get; set; }
            public TradeBalanceObject F0BTC { get; set; }
            public TradeBalanceObject PLCU { get; set; }
            public TradeBalanceObject GULF { get; set; }
            public TradeBalanceObject XRD { get; set; }
            public TradeBalanceObject XRD_RADIX { get; set; }
            public TradeBalanceObject XRD_ETH { get; set; }
            public TradeBalanceObject AVAX_XCHAIN { get; set; }
            public TradeBalanceObject JASMY { get; set; }
            public TradeBalanceObject PEOPLE { get; set; }
            public TradeBalanceObject WOO { get; set; }
            public TradeBalanceObject LOKA { get; set; }
            public TradeBalanceObject IMX { get; set; }
            public TradeBalanceObject NEXO { get; set; }
            public TradeBalanceObject ADX { get; set; }
            public TradeBalanceObject AMP { get; set; }
            public TradeBalanceObject API3 { get; set; }
            public TradeBalanceObject DODO { get; set; }
            public TradeBalanceObject OP { get; set; }
            public TradeBalanceObject AUDIO { get; set; }
            public TradeBalanceObject UNFI { get; set; }
            public TradeBalanceObject OCEAN { get; set; }
            public TradeBalanceObject MBOX { get; set; }
            public TradeBalanceObject CAKE { get; set; }
            public TradeBalanceObject VOXEL { get; set; }
            public TradeBalanceObject CUC { get; set; }
            public TradeBalanceObject ATOM { get; set; }
        }

        public class TradeBalanceObject
        {
            public string available { get; set; }
            public string freeze { get; set; }

        }
        public class MainHistory
        {

            public class Details
            {
                public string requestAmount { get; set; }
                public string processedAmount { get; set; }
                public string processedFee { get; set; }
                public string normalizeTransaction { get; set; }

            }

            public class HistoryData
            {
                public string address { get; set; }
                public string uniqueId { get; set; }
                public string createdAt { get; set; }
                public string currency { get; set; }
                public string ticker { get; set; }
                public string method { get; set; }
                public string amount { get; set; }
                public string description { get; set; }
                public string memo { get; set; }
                public string fee { get; set; }
                public string status { get; set; }
                public string network { get; set; }

                public string transactionHash { get; set; }
                public Details details { get; set; }


            }
            public string total { get; set; }
            public HistoryData[] records { get; set; }
            public string limit { get; set; }
            public string offset { get; set; }
        }


       


    }
}
